### ISSUE TITLE
Add delay between two consecutive battles

### ISSUE THREAD

**Issue by MaximeCheramy** [danBhentschel/CGSpunk#62]
When someone submits a code, the battles are computed on CodinGame's servers with a lower priority than the "plays" in order to make sure that the plays are computed as soon as possible.

CGSpunk simulates a submit by doing plays. As a consequence, people that use CGSpunk slow down the computation for people that just want to test their code... We're afraid that it could prevent people from doing plays at the end of the contest.

We will add a limit on the numbers of calls you can do during an interval of time (the exact value isn't decided yet, we will start with something very gentle first). In order to avoid reaching the limits, I suggest to add a delay between two matches. **A few dozen of seconds should be enough.**

We will implement in the future a more sophisticated solution but the quota was the easy short term solution...

**Comment by danBhentschel** [comment]
Need to make a modification for Firefox.
